<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('thuong_hieu')->insert([
            [
                'ma_thuong_hieu' => 1,
                'ten_thuong_hieu' => 'Honda',
                'duong_dan' => '/thuong-hieu/honda',
                'logo' => '/images/brands/honda.png',
                'mo_ta' => 'Thương hiệu xe máy phổ biến tại Việt Nam, nổi bật với độ bền và tính thực dụng.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(14),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 2,
                'ten_thuong_hieu' => 'Yamaha',
                'duong_dan' => '/thuong-hieu/yamaha',
                'logo' => '/images/brands/yamaha.png',
                'mo_ta' => 'Các dòng xe máy thể thao, trẻ trung và dễ vận hành.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(13),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 3,
                'ten_thuong_hieu' => 'Suzuki',
                'duong_dan' => '/thuong-hieu/suzuki',
                'logo' => '/images/brands/suzuki.png',
                'mo_ta' => 'Xe máy bền bỉ, phù hợp nhu cầu đi lại và thể thao đường phố.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(12),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 4,
                'ten_thuong_hieu' => 'Kawasaki',
                'duong_dan' => '/thuong-hieu/kawasaki',
                'logo' => '/images/brands/kawasaki.png',
                'mo_ta' => 'Mô tô phân khối lớn với hiệu năng mạnh và thiết kế đặc trưng.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(11),
                'ngay_cap_nhat' => $now->copy()->subDays(1),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 5,
                'ten_thuong_hieu' => 'Piaggio',
                'duong_dan' => '/thuong-hieu/piaggio',
                'logo' => '/images/brands/piaggio.png',
                'mo_ta' => 'Xe tay ga phong cách châu Âu, phù hợp di chuyển đô thị.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(10),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 6,
                'ten_thuong_hieu' => 'LS2',
                'duong_dan' => '/thuong-hieu/ls2',
                'logo' => '/images/brands/ls2.png',
                'mo_ta' => 'Thương hiệu mũ bảo hiểm được ưa chuộng cho đi phố và đi tour.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(9),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 7,
                'ten_thuong_hieu' => 'Motul',
                'duong_dan' => '/thuong-hieu/motul',
                'logo' => '/images/brands/motul.png',
                'mo_ta' => 'Dầu nhớt và dung dịch bảo dưỡng cho xe máy chất lượng cao.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(8),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thuong_hieu' => 8,
                'ten_thuong_hieu' => 'Givi',
                'duong_dan' => '/thuong-hieu/givi',
                'logo' => '/images/brands/givi.png',
                'mo_ta' => 'Phụ kiện touring, thùng xe và trang bị tiện ích cho biker.',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(7),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ]);

        DB::table('danh_muc')->insert([
            [
                'ma_danh_muc' => 1,
                'ten_danh_muc' => 'Xe tay ga',
                'duong_dan' => '/danh-muc/xe-tay-ga',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Các mẫu xe tay ga phù hợp đi làm, đi học và di chuyển trong phố.',
                'anh_dai_dien' => '/images/categories/xe-tay-ga.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(14),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 2,
                'ten_danh_muc' => 'Xe số',
                'duong_dan' => '/danh-muc/xe-so',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Dòng xe tiết kiệm nhiên liệu, bền bỉ và dễ sử dụng.',
                'anh_dai_dien' => '/images/categories/xe-so.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(13),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 3,
                'ten_danh_muc' => 'Xe côn tay',
                'duong_dan' => '/danh-muc/xe-con-tay',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Mẫu xe dành cho người thích cảm giác lái mạnh và thể thao.',
                'anh_dai_dien' => '/images/categories/xe-con-tay.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(12),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 4,
                'ten_danh_muc' => 'Mô tô phân khối lớn',
                'duong_dan' => '/danh-muc/mo-to-phan-khoi-lon',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Xe mô tô cho nhu cầu trải nghiệm, tốc độ và đi tour dài.',
                'anh_dai_dien' => '/images/categories/mo-to-phan-khoi-lon.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(11),
                'ngay_cap_nhat' => $now->copy()->subDays(1),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 5,
                'ten_danh_muc' => 'Mũ bảo hiểm',
                'duong_dan' => '/danh-muc/mu-bao-hiem',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Mũ bảo hiểm fullface, 3/4 và nửa đầu cho biker.',
                'anh_dai_dien' => '/images/categories/mu-bao-hiem.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(10),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 6,
                'ten_danh_muc' => 'Dầu nhớt',
                'duong_dan' => '/danh-muc/dau-nhot',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Dầu nhớt và dung dịch chăm sóc xe máy.',
                'anh_dai_dien' => '/images/categories/dau-nhot.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(9),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 7,
                'ten_danh_muc' => 'Phụ kiện touring',
                'duong_dan' => '/danh-muc/phu-kien-touring',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Phụ kiện phục vụ đi tour, chở đồ và nâng trải nghiệm lái xe.',
                'anh_dai_dien' => '/images/categories/phu-kien-touring.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(8),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 8,
                'ten_danh_muc' => 'Phụ tùng',
                'duong_dan' => '/danh-muc/phu-tung',
                'ma_danh_muc_cha' => null,
                'mo_ta' => 'Phụ tùng thay thế và linh kiện cho xe máy.',
                'anh_dai_dien' => '/images/categories/phu-tung.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(7),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ]);

        DB::table('danh_muc')->insert([
            [
                'ma_danh_muc' => 9,
                'ten_danh_muc' => 'Thùng xe',
                'duong_dan' => '/danh-muc/thung-xe',
                'ma_danh_muc_cha' => 7,
                'mo_ta' => 'Thùng giữa, thùng sau và giải pháp chở đồ cho xe touring.',
                'anh_dai_dien' => '/images/categories/thung-xe.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(6),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_danh_muc' => 10,
                'ten_danh_muc' => 'Kính chắn gió',
                'duong_dan' => '/danh-muc/kinh-chan-gio',
                'ma_danh_muc_cha' => 7,
                'mo_ta' => 'Kính chắn gió hỗ trợ đi xa, giảm gió và tăng sự thoải mái.',
                'anh_dai_dien' => '/images/categories/kinh-chan-gio.jpg',
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(5),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ]);

        DB::table('thanh_dieu_huong')->insert([
            [
                'ma_thanh_dieu_huong' => 1,
                'ten_hien_thi' => 'Trang chủ',
                'duong_dan' => '/',
                'ma_thanh_dieu_huong_cha' => null,
                'thu_tu_hien_thi' => 1,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(14),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 2,
                'ten_hien_thi' => 'Xe máy',
                'duong_dan' => '/san-pham',
                'ma_thanh_dieu_huong_cha' => null,
                'thu_tu_hien_thi' => 2,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(13),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 8,
                'ten_hien_thi' => 'Tin tức',
                'duong_dan' => '/bai-viet',
                'ma_thanh_dieu_huong_cha' => null,
                'thu_tu_hien_thi' => 8,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(8),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 9,
                'ten_hien_thi' => 'Khuyến mãi',
                'duong_dan' => '/khuyen-mai',
                'ma_thanh_dieu_huong_cha' => null,
                'thu_tu_hien_thi' => 9,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(7),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 10,
                'ten_hien_thi' => 'Liên hệ',
                'duong_dan' => '/lien-he',
                'ma_thanh_dieu_huong_cha' => null,
                'thu_tu_hien_thi' => 10,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(6),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ]);

        DB::table('thanh_dieu_huong')->insert([
            [
                'ma_thanh_dieu_huong' => 3,
                'ten_hien_thi' => 'Xe tay ga',
                'duong_dan' => '/san-pham/xe-tay-ga',
                'ma_thanh_dieu_huong_cha' => 2,
                'thu_tu_hien_thi' => 3,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(12),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 4,
                'ten_hien_thi' => 'Xe số',
                'duong_dan' => '/san-pham/xe-so',
                'ma_thanh_dieu_huong_cha' => 2,
                'thu_tu_hien_thi' => 4,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(11),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 5,
                'ten_hien_thi' => 'Xe côn tay',
                'duong_dan' => '/san-pham/xe-con-tay',
                'ma_thanh_dieu_huong_cha' => 2,
                'thu_tu_hien_thi' => 5,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(10),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 6,
                'ten_hien_thi' => 'Mô tô PKL',
                'duong_dan' => '/san-pham/mo-to-phan-khoi-lon',
                'ma_thanh_dieu_huong_cha' => 2,
                'thu_tu_hien_thi' => 6,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(9),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_thanh_dieu_huong' => 7,
                'ten_hien_thi' => 'Phụ kiện',
                'duong_dan' => '/san-pham/phu-kien-touring',
                'ma_thanh_dieu_huong_cha' => 2,
                'thu_tu_hien_thi' => 7,
                'trang_thai' => 'hoat_dong',
                'ngay_tao' => $now->copy()->subDays(8),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ]);
    }
}
