<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DonHangSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('don_hang')->insert([
            [
                'ma_don_hang' => 1,
                'ma_nguoi_dung' => 3,
                'ho_ten' => 'Nguyễn Văn Sơn',
                'dia_chi_email' => 'son@motohub.vn',
                'so_dien_thoai' => '0909000003',
                'dia_chi_giao_hang' => '88 Trần Hưng Đạo, Phường 6, Quận 5, TP.HCM',
                'phuong_thuc_thanh_toan' => 'tra_gop',
                'ma_giao_dich' => null,
                'ghi_chu' => 'Cần hỗ trợ hồ sơ trả góp khi nhận xe.',
                'tam_tinh' => 60480000.00,
                'giam_gia' => 480000.00,
                'tong_tien' => 60000000.00,
                'trang_thai' => 'cho_xac_nhan',
                'trang_thai_thanh_toan' => 'chua_thanh_toan',
                'ngay_tao' => $now->copy()->subDays(2),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_don_hang' => 2,
                'ma_nguoi_dung' => null,
                'ho_ten' => 'Trần Thị Mai',
                'dia_chi_email' => 'mai.tran@example.com',
                'so_dien_thoai' => '0911222333',
                'dia_chi_giao_hang' => '45 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
                'phuong_thuc_thanh_toan' => 'chuyen_khoan',
                'ma_giao_dich' => 'VNPAY2609080001',
                'ghi_chu' => 'Giao xe vào buổi chiều, gọi trước khi đến.',
                'tam_tinh' => 194268000.00,
                'giam_gia' => 268000.00,
                'tong_tien' => 194000000.00,
                'trang_thai' => 'dang_xu_ly',
                'trang_thai_thanh_toan' => 'da_thanh_toan',
                'ngay_tao' => $now->copy()->subDay(),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_don_hang' => 3,
                'ma_nguoi_dung' => 3,
                'ho_ten' => 'Nguyễn Văn Sơn',
                'dia_chi_email' => 'son@motohub.vn',
                'so_dien_thoai' => '0909000003',
                'dia_chi_giao_hang' => '88 Trần Hưng Đạo, Phường 6, Quận 5, TP.HCM',
                'phuong_thuc_thanh_toan' => 'tien_mat',
                'ma_giao_dich' => null,
                'ghi_chu' => 'Gắn sẵn thùng Givi khi giao xe.',
                'tam_tinh' => 39446000.00,
                'giam_gia' => 446000.00,
                'tong_tien' => 39000000.00,
                'trang_thai' => 'da_giao',
                'trang_thai_thanh_toan' => 'da_thanh_toan',
                'ngay_tao' => $now->copy()->subHours(18),
                'ngay_cap_nhat' => $now->copy()->subHours(6),
                'ngay_xoa' => null,
            ],
        ]);

        DB::table('chi_tiet_don_hang')->insert([
            [
                'ma_chi_tiet_don_hang' => 1,
                'ma_don_hang' => 1,
                'ma_san_pham' => 1,
                'ten_san_pham' => 'Honda SH Mode 125i 2025',
                'so_luong' => 1,
                'don_gia' => 52900000.00,
                'thanh_tien' => 52900000.00,
                'ngay_tao' => $now->copy()->subDays(2),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 2,
                'ma_don_hang' => 1,
                'ma_san_pham' => 7,
                'ten_san_pham' => 'LS2 FF800 Storm II',
                'so_luong' => 2,
                'don_gia' => 3790000.00,
                'thanh_tien' => 7580000.00,
                'ngay_tao' => $now->copy()->subDays(2),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 3,
                'ma_don_hang' => 2,
                'ma_san_pham' => 5,
                'ten_san_pham' => 'Kawasaki Ninja 500 2025',
                'so_luong' => 1,
                'don_gia' => 189900000.00,
                'thanh_tien' => 189900000.00,
                'ngay_tao' => $now->copy()->subDay(),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 4,
                'ma_don_hang' => 2,
                'ma_san_pham' => 7,
                'ten_san_pham' => 'LS2 FF800 Storm II',
                'so_luong' => 1,
                'don_gia' => 3790000.00,
                'thanh_tien' => 3790000.00,
                'ngay_tao' => $now->copy()->subDay(),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 5,
                'ma_don_hang' => 2,
                'ma_san_pham' => 8,
                'ten_san_pham' => 'Motul 5100 10W40 1L',
                'so_luong' => 2,
                'don_gia' => 289000.00,
                'thanh_tien' => 578000.00,
                'ngay_tao' => $now->copy()->subDay(),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 6,
                'ma_don_hang' => 3,
                'ma_san_pham' => 3,
                'ten_san_pham' => 'Honda Wave Alpha 110 2025',
                'so_luong' => 2,
                'don_gia' => 17900000.00,
                'thanh_tien' => 35800000.00,
                'ngay_tao' => $now->copy()->subHours(18),
                'ngay_cap_nhat' => $now->copy()->subHours(6),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 7,
                'ma_don_hang' => 3,
                'ma_san_pham' => 9,
                'ten_san_pham' => 'Givi B32N',
                'so_luong' => 1,
                'don_gia' => 2490000.00,
                'thanh_tien' => 2490000.00,
                'ngay_tao' => $now->copy()->subHours(18),
                'ngay_cap_nhat' => $now->copy()->subHours(6),
                'ngay_xoa' => null,
            ],
            [
                'ma_chi_tiet_don_hang' => 8,
                'ma_don_hang' => 3,
                'ma_san_pham' => 8,
                'ten_san_pham' => 'Motul 5100 10W40 1L',
                'so_luong' => 4,
                'don_gia' => 289000.00,
                'thanh_tien' => 1156000.00,
                'ngay_tao' => $now->copy()->subHours(18),
                'ngay_cap_nhat' => $now->copy()->subHours(6),
                'ngay_xoa' => null,
            ],
        ]);
    }
}
