<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanPhamSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $products = [
            [
                'ma_san_pham' => 1,
                'ten_san_pham' => 'Honda SH Mode 125i 2025',
                'ma_danh_muc' => 1,
                'ma_thuong_hieu' => 1,
                'duong_dan' => '/honda-sh-mode-125i-2025',
                'gia_ban' => 54900000.00,
                'gia_khuyen_mai' => 52900000.00,
                'so_luong_ton' => 6,
                'dung_tich_dong_co' => 125,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Đỏ đô',
                'anh_dai_dien' => '/images/products/honda-sh-mode-125i-2025-1.jpg',
                'mo_ta' => 'Mẫu xe tay ga cao cấp phù hợp di chuyển trong phố, thiết kế sang và vận hành êm ái.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 214,
                'ngay_tao' => $now->copy()->subDays(14),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 2,
                'ten_san_pham' => 'Yamaha Exciter 155 VVA 2025',
                'ma_danh_muc' => 3,
                'ma_thuong_hieu' => 2,
                'duong_dan' => '/yamaha-exciter-155-vva-2025',
                'gia_ban' => 54900000.00,
                'gia_khuyen_mai' => 52900000.00,
                'so_luong_ton' => 8,
                'dung_tich_dong_co' => 155,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Xanh GP',
                'anh_dai_dien' => '/images/products/yamaha-exciter-155-vva-2025-1.jpg',
                'mo_ta' => 'Xe côn tay thể thao, tăng tốc tốt và phù hợp người thích cảm giác lái mạnh.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 186,
                'ngay_tao' => $now->copy()->subDays(13),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 3,
                'ten_san_pham' => 'Honda Wave Alpha 110 2025',
                'ma_danh_muc' => 2,
                'ma_thuong_hieu' => 1,
                'duong_dan' => '/honda-wave-alpha-110-2025',
                'gia_ban' => 18500000.00,
                'gia_khuyen_mai' => 17900000.00,
                'so_luong_ton' => 20,
                'dung_tich_dong_co' => 110,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Đỏ',
                'anh_dai_dien' => '/images/products/honda-wave-alpha-110-2025-1.jpg',
                'mo_ta' => 'Xe số tiết kiệm nhiên liệu, bền bỉ và dễ sử dụng cho nhu cầu đi lại hằng ngày.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 149,
                'ngay_tao' => $now->copy()->subDays(12),
                'ngay_cap_nhat' => $now->copy()->subDays(1),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 4,
                'ten_san_pham' => 'Suzuki Raider R150 2025',
                'ma_danh_muc' => 3,
                'ma_thuong_hieu' => 3,
                'duong_dan' => '/suzuki-raider-r150-2025',
                'gia_ban' => 49900000.00,
                'gia_khuyen_mai' => 47900000.00,
                'so_luong_ton' => 10,
                'dung_tich_dong_co' => 150,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Đen đỏ',
                'anh_dai_dien' => '/images/products/suzuki-raider-r150-2025-1.jpg',
                'mo_ta' => 'Mẫu xe underbone thiên về tốc độ, nhẹ và linh hoạt trong đô thị.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 122,
                'ngay_tao' => $now->copy()->subDays(11),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 5,
                'ten_san_pham' => 'Kawasaki Ninja 500 2025',
                'ma_danh_muc' => 4,
                'ma_thuong_hieu' => 4,
                'duong_dan' => '/kawasaki-ninja-500-2025',
                'gia_ban' => 194900000.00,
                'gia_khuyen_mai' => 189900000.00,
                'so_luong_ton' => 2,
                'dung_tich_dong_co' => 451,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Xanh lá',
                'anh_dai_dien' => '/images/products/kawasaki-ninja-500-2025-1.jpg',
                'mo_ta' => 'Mẫu mô tô phân khối lớn cho người chơi xe, thiết kế mạnh mẽ và phù hợp đi tour.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 231,
                'ngay_tao' => $now->copy()->subDays(10),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 6,
                'ten_san_pham' => 'Piaggio Liberty S 125 2025',
                'ma_danh_muc' => 1,
                'ma_thuong_hieu' => 5,
                'duong_dan' => '/piaggio-liberty-s-125-2025',
                'gia_ban' => 59900000.00,
                'gia_khuyen_mai' => 57900000.00,
                'so_luong_ton' => 5,
                'dung_tich_dong_co' => 125,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Trắng',
                'anh_dai_dien' => '/images/products/piaggio-liberty-s-125-2025-1.jpg',
                'mo_ta' => 'Xe tay ga phong cách châu Âu, gọn và phù hợp di chuyển trong thành phố.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 167,
                'ngay_tao' => $now->copy()->subDays(9),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 7,
                'ten_san_pham' => 'LS2 FF800 Storm II',
                'ma_danh_muc' => 5,
                'ma_thuong_hieu' => 6,
                'duong_dan' => '/ls2-ff800-storm-ii',
                'gia_ban' => 4200000.00,
                'gia_khuyen_mai' => 3790000.00,
                'so_luong_ton' => 35,
                'dung_tich_dong_co' => null,
                'nam_san_xuat' => 2025,
                'mau_sac' => 'Đen mờ',
                'anh_dai_dien' => '/images/products/ls2-ff800-storm-ii-1.jpg',
                'mo_ta' => 'Mũ bảo hiểm fullface cho nhu cầu đi phố lẫn đi tour dài ngày.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 98,
                'ngay_tao' => $now->copy()->subDays(8),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 8,
                'ten_san_pham' => 'Motul 5100 10W40 1L',
                'ma_danh_muc' => 6,
                'ma_thuong_hieu' => 7,
                'duong_dan' => '/motul-5100-10w40-1l',
                'gia_ban' => 320000.00,
                'gia_khuyen_mai' => 289000.00,
                'so_luong_ton' => 120,
                'dung_tich_dong_co' => null,
                'nam_san_xuat' => 2025,
                'mau_sac' => null,
                'anh_dai_dien' => '/images/products/motul-5100-10w40-1l-1.jpg',
                'mo_ta' => 'Dầu nhớt bán tổng hợp cho xe số, xe côn tay và xe tay ga.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 76,
                'ngay_tao' => $now->copy()->subDays(7),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 9,
                'ten_san_pham' => 'Givi B32N',
                'ma_danh_muc' => 9,
                'ma_thuong_hieu' => 8,
                'duong_dan' => '/givi-b32n',
                'gia_ban' => 2850000.00,
                'gia_khuyen_mai' => 2490000.00,
                'so_luong_ton' => 18,
                'dung_tich_dong_co' => null,
                'nam_san_xuat' => 2024,
                'mau_sac' => 'Đen',
                'anh_dai_dien' => '/images/products/givi-b32n-1.jpg',
                'mo_ta' => 'Thùng xe dung tích gọn, phù hợp đi làm hằng ngày và chở đồ an toàn.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 142,
                'ngay_tao' => $now->copy()->subDays(6),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
            [
                'ma_san_pham' => 10,
                'ten_san_pham' => 'Givi Airflow',
                'ma_danh_muc' => 10,
                'ma_thuong_hieu' => 8,
                'duong_dan' => '/givi-airflow',
                'gia_ban' => 1450000.00,
                'gia_khuyen_mai' => 1290000.00,
                'so_luong_ton' => 14,
                'dung_tich_dong_co' => null,
                'nam_san_xuat' => 2024,
                'mau_sac' => 'Trong suốt',
                'anh_dai_dien' => '/images/products/givi-airflow-1.jpg',
                'mo_ta' => 'Kính chắn gió giúp giảm gió tạt, tăng sự thoải mái khi đi xa.',
                'trang_thai' => 'hoat_dong',
                'luot_xem' => 88,
                'ngay_tao' => $now->copy()->subDays(5),
                'ngay_cap_nhat' => $now->copy()->subDay(),
                'ngay_xoa' => null,
            ],
        ];

        DB::table('san_pham')->insert($products);

        $images = [];
        $imageId = 1;

        foreach ($products as $product) {
            $slug = ltrim($product['duong_dan'], '/');

            $images[] = [
                'ma_hinh_anh' => $imageId++,
                'ma_san_pham' => $product['ma_san_pham'],
                'duong_dan' => "/images/products/{$slug}-1.jpg",
                'la_anh_dai_dien' => true,
                'thu_tu_hien_thi' => 1,
                'ngay_tao' => $now->copy()->subDays(4),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ];

            $images[] = [
                'ma_hinh_anh' => $imageId++,
                'ma_san_pham' => $product['ma_san_pham'],
                'duong_dan' => "/images/products/{$slug}-2.jpg",
                'la_anh_dai_dien' => false,
                'thu_tu_hien_thi' => 2,
                'ngay_tao' => $now->copy()->subDays(4),
                'ngay_cap_nhat' => $now->copy()->subDays(2),
                'ngay_xoa' => null,
            ];
        }

        DB::table('hinh_anh_san_pham')->insert($images);
    }
}
